import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";
import { url } from "inspector";

export const metadata: Metadata = {
  title: "Learn Next JS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  const menuItem = (url: string, title: string) => (
    <li className="bg-orange-400 text-white py-2 p-3 rounded-lg hover:bg-orange-500">
      <Link href={url}>{title}</Link>
    </li>
  )

  return (
    <html lang="en">
      <body className="container mx-auto">
        <nav>
          <ul className="flex gap-2 justify-center p-2">
            {menuItem('/', 'Home')}
            {menuItem('/dashboard', 'Dashboard')}
            {menuItem('/calculator', 'Calculator')}
            {menuItem('/users', 'Users')}
            {menuItem('/settings', 'Settings')}
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
